### ISSUE TITLE
Upgrade .NET requirement to v6 or newer

### ISSUE THREAD

**Issue by duncand** [bcgov/PIMS#1407]
The PIMS .NET components currently target .NET version 5 but they should target .NET version 6 or 7 instead.

(Likewise for every other bcgov project still targeting a .NET Core version prior to 6.)

One key reason for this is that .NET 5 is no longer supported by Microsoft and so depending on it presents a security risk.

Another key reason is that .NET 6 and later are explicitly compatible with Apple Macintoshes using M1 chips, unlike .NET 5, and so PIMS using .NET 6 or newer means that PIMS can be developed and run on the latest Macs.

Since all modern versions of .NET are backwards compatible with prior .NET Core versions, changing the project targets from net5 to net6 or net7 should be trivial.  Its not like migrating from .NET Framework.

The setup instructions on https://github.com/bcgov/PIMS/wiki/Development explicitly say things won't work on M1, but shouldn't.

The comment about `brew install coreutils` will not work on M1 is obsolete.

I have already mostly successfully built PIMS on my own M1 Mac, which had handled my already installed .NET 7 just fine.  Though the Docker build step failed because it was explicitly still trying to use .NET 5 which didn't exist for M1s, and this should pass if the config only tried to use a newer .NET instead.

I might be able to provide a pull request to fix this myself, but will have to talk with devs to get certain secrets or seed data that I otherwise would need to run it first.  But it may be trivial for an existing PIMS dev to do first.

**Comment by LawrenceLau2020** [comment]
Thanks for the heads up, Duncan, we're aware of this issue and will be updating to .NET version 6 fairly soon.

**Comment by LawrenceLau2020** [comment]
Upgraded to .NET v6
