### ISSUE TITLE
Geo-spatial Real Estate Inventory System

### ISSUE THREAD

**Issue by bcdevex** [bcgov/PIMS#2]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/swu/opp-geospatial-real-estate-inventory-system"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/swu/opp-geospatial-real-estate-inventory-system">visit the opportunity page</a>.
The opportunity closes on <b>Wednesday, December 11th, 2019 at 16:00 PST</b>.</p>

**Comment by countable** [comment]
Hello there;

Our team has 2 questions about this opportunity.

1. We see .NET specified as a required capability and are wondering if it's set in stone as the back-end, or if a more open, and GIS-oriented back-end stack would be considered with a small .NET adapter for legacy system connections? We could work either way, but recommend evaluating the right tools for the best outcome during the inception phase.

2. We see in-person work is required. Would a Vancouver-based team be considered if we can keep at minimum one person in Victoria (whom it is would be dependent on the project phase) at all times during the project?

**Comment by ZachWoodward** [comment]
Question:.NET specified as a required capability and are wondering if it's set in stone as the back-end, or if a more open, and GIS-oriented back-end stack would be considered with a small .NET adapter for legacy system connections? We could work either way, but recommend evaluating the right tools for the best outcome during the inception phase.

Answer: .NET is not a hard requirement.  There are other back-end technologies listed, such as Node.js and Python Flask, which would be acceptable as well.

**Comment by ZachWoodward** [comment]
Question: We see in-person work is required. Would a Vancouver-based team be considered if we can keep at minimum one person in Victoria (whom it is would be dependent on the project phase) at all times during the project?

Answer: Please see Addenda 1. The Product Owner is seeking a core team to be on site. One person in Victoria would be insufficient to meet this expectation.

**Comment by nzorkin** [comment]
Question: Would you accept an existing software solution that matches your requirements for this opportunity?

**Comment by ZachWoodward** [comment]
Multiple options for solutions were explored including posting an RFI where we received feedback from vendors including implementing existing software. The executive decision to create the PIMS product from the ground up at the Exchange Lab in collaboration with vendors was made based on the following:

•	Build internal capacity
o	To build off of the experience of other teams in the lab 
o	For the coaching, training, and support available 
o	To be continuously improving the system to meet future functionality requirements
•	Build digital competency
•	Build code in the open
o	Re-use that code when possible
•	Supports the BC Government’s Digital Framework  https://digital.gov.bc.ca/
•	Partner across and beyond government to support the open collaboration, engagement and enablement of better service delivery
•	Share and mentor and create community

**Comment by nzorkin** [comment]
Thank you for your response and we understand your position. If future opportunities arise, please note that ENKON has been building and implementing land information systems since 2005. We have implemented over thirty systems in the last ten years and have a team of thirty staff who focus on land management. We currently have fifteen modules specific to land management processes including a mapping module providing geo-spatial functionality . Our systems have been deployed around the world and we have recently worked with Metro Vancouver to deliver a system to manage all of their land assets. I would be pleased to provide more information if requested.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by ZachWoodward** [comment]
Apologies for the duplicate notification. Preparing the contract and accidentally re-notified.
