### ISSUE TITLE
[Issue]: Active Inventory doesnt filter by Land

### ISSUE THREAD

**Issue by BradyMitch** [bcgov/PIMS#2492]
### Details

Filtering the Active Inventory by land shows no results, even though filtering for All Properties shows parcels.

https://pims-v2-dev.apps.silver.devops.gov.bc.ca/properties?quickSelectFilter=Land&columnFilterName=PropertyType&columnFilterValue=Land&columnFilterMode=contains

### Steps to Reproduce (Optional)

1. Go to "Active Inventory" page.
2. Select "Land" in the dropdown filter.

### Issue Type

Unexpected Behaviour

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you using?

Windows

### Environment (Optional)

Dev

**Comment by dbarkowsky** [comment]
Good catch. Got this one in before the PR went through. 😆

**Comment by GrahamS-Quartech** [comment]
Not sure which PR this was exactly but closing as it's definitely fixed.
