### ISSUE TITLE
[Issue]: Active inventory export crashes

### ISSUE THREAD

**Issue by BradyMitch** [bcgov/PIMS#2493]
### Details

Export to Excel on Active Inventory tab errors when no filters are applied. 

Possibly too large of an export. (Exports without Issue when filtering by Building only)

![pims-export-error](https://github.com/bcgov/PIMS/assets/16313579/1745f1e8-2721-458a-bd01-47bde89a248b)

### Steps to Reproduce (Optional)

1. Go to "Active Inventory" page.
2. Click "Export to Excel" button.

### Issue Type

Unexpected Behaviour

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you using?

Windows

### Environment (Optional)

Dev

**Comment by GrahamS-Quartech** [comment]
Fixed by: https://github.com/bcgov/PIMS/pull/2535
