### ISSUE TITLE
[Issue]: Create new property padding

### ISSUE THREAD

**Issue by BradyMitch** [bcgov/PIMS#2494]
### Details

The Add New Property page submit button needs some padding or margin under it because it sits directly on the bottom of the screen.

![pims-padding](https://github.com/bcgov/PIMS/assets/16313579/80d76131-87e0-4c50-8912-6cc2cabdab26)

### Steps to Reproduce (Optional)

1. Go to "Active Inventory" tab.
2. Click on "Create New Property" ("+") button.
3. Scroll to bottom of page.

### Issue Type

Visual

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you using?

Windows

### Environment (Optional)

Dev

**Comment by GrahamS-Quartech** [comment]
Solved by https://github.com/bcgov/PIMS/pull/2500
