### ISSUE TITLE
[Issue]: Add property should indicate PID/PIN are required

### ISSUE THREAD

**Issue by BradyMitch** [bcgov/PIMS#2495]
### Details

There is no indication that the PID and PIN fields are required except for the text "PID (Parcel Identifier) is required to proceed." when selecting a property type. Usually a "*" is added next to required fields. Only once trying to submit the form do you get an error saying it is required.

![pims-required-fields](https://github.com/bcgov/PIMS/assets/16313579/d052b127-b7c4-4ca9-9f64-c8d8babe7bd5)

### Steps to Reproduce (Optional)

1. Go to "Active Inventory" tab.
2. Click on "Create New Property" ("+") button.
3. Scroll down to "Address" section.

### Issue Type

Visual

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you using?

Windows

### Environment (Optional)

Dev

**Comment by TaylorFries** [comment]
being resolved in https://github.com/bcgov/PIMS/pull/2563
