### ISSUE TITLE
[Issue]: Cannot set location with map for "Create New Property"

### ISSUE THREAD

**Issue by BradyMitch** [bcgov/PIMS#2498]
### Details

Under the map it says "Fill fields or drag map to set location."

I can drag the map, zoom in on a parcel and even click on the parcel to see its PID but it does not set location.

Needs added functionality or changed language to suggest that the map can be used to find a PID.

### Steps to Reproduce (Optional)

1. Open "Active Inventory" tab.
2. Click on "Create New Property" ("+") button.
3. Scroll down to the map.
4. Move and zoom the map to a property, and click.

### Issue Type

Visual

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you using?

Windows

### Environment (Optional)

Dev

**Comment by GrahamS-Quartech** [comment]
Fixed by: https://github.com/bcgov/PIMS/pull/2566
