### ISSUE TITLE
[Issue]: Loading spinner displayed on authenticated app routes when not logged in

### ISSUE THREAD

**Issue by antsand** [bcgov/PIMS#2524]
### Details

![image](https://github.com/bcgov/PIMS/assets/8980101/c457c313-124e-4178-97fe-a375bae40ba1)

page seems unresponsive when i first signed in. 

this is the url where we have this issue: https://pims-v2-dev.apps.silver.devops.gov.bc.ca/access-request

### Issue Type

Visual

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you using?

Windows

### Environment (Optional)

None

**Comment by GrahamS-Quartech** [comment]
Solved by: https://github.com/bcgov/PIMS/pull/2559
This issue is due to a limitation of the CITZ SSO package. We may improve on the handling of this case further in the future.
