### ISSUE TITLE
[Issue]: Disposal projects excel export crashes

### ISSUE THREAD

**Issue by Aman-Hundal** [bcgov/PIMS#2529]
### Contact Details (Optional)

aman.hundal@gov.bc.ca

### Details

Outcome -> After downloading excel, an error is logged in console and page goes to blank screen. Excel is downloaded
Expected Outcome -> After downloading excel, user should be kept on the same page and excel should be downloaded.

SEE CONSOLE ERROR BELOW:
![image](https://github.com/bcgov/PIMS/assets/64342261/8d949c5a-00d5-4900-910b-7125290cdb60)

### Steps to Reproduce (Optional)

1. Go to the Disposal Projects Tab
2. Select the download icon to download the excel
3. ERROR = Screen refreshes to blank page with a console error about pimsUser. The excel is downloaded and appears to be fine however.

### Issue Type

Unexpected Behaviour

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you using?

Windows

### Environment (Optional)

Dev

**Comment by GrahamS-Quartech** [comment]
Related: https://github.com/bcgov/PIMS/issues/2493

**Comment by GrahamS-Quartech** [comment]
Fixed by: https://github.com/bcgov/PIMS/pull/2535
