### ISSUE TITLE
[Issue]: Last login may not be populated in some cases

### ISSUE THREAD

**Issue by antsand** [bcgov/PIMS#2530]
### Details

![image](https://github.com/bcgov/PIMS/assets/8980101/590d9c54-c507-4e71-b7c8-2de010ee2cae)

### Steps to Reproduce (Optional)

![image](https://github.com/bcgov/PIMS/assets/8980101/21453b4d-a57e-454d-9746-72375e9ff0de)

last login is not recorded. Also, you technically should not be able to edit your profile info if it is based on IDIR. 

### Issue Type

Visual

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you using?

Windows

### Environment (Optional)

None

**Comment by GrahamS-Quartech** [comment]
Fixed by: https://github.com/bcgov/PIMS/pull/2584
