### ISSUE TITLE
[Issue]: Bulk upload does not provide appropriate feedback when invalid file is uploaded

### ISSUE THREAD

**Issue by Aman-Hundal** [bcgov/PIMS#2533]
### Contact Details (Optional)

aman.hundal@gov.bc.ca

### Details

![image](https://github.com/user-attachments/assets/be231125-7192-40d8-aafd-838d52672f85)

The .msg file contains a xls, pdf, and png as attachments. The network calls are looping with a 304 status and the file is stuck in processing for atleast 20 mins plus

### Steps to Reproduce (Optional)

1. Go to the bulk uploads tab. 
2. Drag and drop a .msg file
3. The page is stuck in a processing loop 

Should an error message appear after X amount of time if a non supportive file type is uploaded? If not it would be great to give some type of error to the user and stop the processing if a an incompatible file is uploaded (a non .csv). 

### Issue Type

Unexpected Behaviour

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you using?

Windows

### Environment (Optional)

None

**Comment by GrahamS-Quartech** [comment]
Fixed by: https://github.com/bcgov/PIMS/pull/2540
