### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [bcgov/PIMS#279]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by Fosol** [comment]
Love to do this but the owners of the GitHub organization would need to install the GitHub app integration, it's not possible at the repo level as far as I know.

**Comment by thomasrockhu** [comment]
Thanks here @Fosol, I think you should be able to request it by repository [here](https://codecov.io/gh/bcgov/PIMS/settings). `bcgov` is already using the integration, but not for this particular repository.

![image](https://user-images.githubusercontent.com/4213028/84973090-3cfadd00-b0ee-11ea-85f4-5d7942693f47.png)

Let me know if that doesn't work!

**Comment by Fosol** [comment]
I've updated, let me know if I need to do anything else?
