### ISSUE TITLE
Broken link on GitHub Workflow Wiki page

### ISSUE THREAD

**Issue by sbathgate** [bcgov/PIMS#741]
I was just looking through the Wiki, which as mentioned over on the RC kudos is super impressive. Just wanted to point out a broken link I came across. It is located [here](https://github.com/bcgov/PIMS/wiki/GitHub-Workflow#attribution) the href currently points to: `https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow` and it should point to: `https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md`.

I'd have drafted a PR, but those aren't an option for Wiki pages.

**Comment by Fosol** [comment]
Thanks for the find!  I've updated the wiki.
